
platform :ios, '8.0'

target 'Example' do
  use_frameworks!

  pod 'FloatyActivityIndicatorController'

  target 'ExampleTests' do
    inherit! :search_paths
  end

  target 'ExampleUITests' do
    inherit! :search_paths
  end

end
